name: Build Electron App for Windows

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Windows App
        run: npm run build:win

      - name: Upload .exe Installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist/*.exe
